name: 'Generic Kubernetes client (kubectl) with AWS cli'
description: 'GitHub Action for interacting with kubectl being possible to authenticate to an EKS cluster via aws cli'
author: 'AK'
branding:
  icon: 'terminal'
  color: 'blue'
inputs:
  EKS_NAME:
    description: 'EKS Cluster Name'
runs:
  using: 'docker'
  image: 'Dockerfile'
